IMG_BLACK = "https://static.prod-images.emergentagent.com/jobs/a8df6e5f-1344-4913-b2d1-d8b4f18b5a89/images/fed8e36a0c3020169a22eb39fe5ded0ec64f3b5d5c3cf23352cb83f95591f29b.jpeg"
IMG_BLUE = "https://static.prod-images.emergentagent.com/jobs/a8df6e5f-1344-4913-b2d1-d8b4f18b5a89/images/cd6ad04f0ca592b2ee7161cbf874c77ab8da771bbcc5d39351be6b8c1d457e66.jpeg"
IMG_HERO = "https://static.prod-images.emergentagent.com/jobs/a8df6e5f-1344-4913-b2d1-d8b4f18b5a89/images/d62b56a508392b78bd69ec9678bab8c3a375fdae70b3853c9ce9e22fa8b3e3b6.jpeg"
IMG_IVORY = "https://static.prod-images.emergentagent.com/jobs/a8df6e5f-1344-4913-b2d1-d8b4f18b5a89/images/85190cadedb8174d0d9a64684f76c2a9841508bbde6968d443f996c76661835e.jpeg"
IMG_VIOLET = "https://static.prod-images.emergentagent.com/jobs/a8df6e5f-1344-4913-b2d1-d8b4f18b5a89/images/9b09f9b584017cfd98eef6f79a7dcb5f4e71418c38b1e3ab61c47fc46da09413.jpeg"
IMG_TEAL = "https://static.prod-images.emergentagent.com/jobs/a8df6e5f-1344-4913-b2d1-d8b4f18b5a89/images/4b7785f8d618b84c968edd2fef132bf03a447d79e1364d262c4dd0860e0a77c6.jpeg"

ALL_SIZES = ["XS", "S", "M", "L", "XL", "XXL"]


def tiers(price):
    return [
        {"label": "1-4 cases", "min_cases": 1, "price_per_box": round(price, 2)},
        {"label": "5-19 cases", "min_cases": 5, "price_per_box": round(price * 0.92, 2)},
        {"label": "20+ cases", "min_cases": 20, "price_per_box": round(price * 0.85, 2)},
    ]


def sizes(available, out_of=None, low=None):
    out_of = out_of or []
    low = low or []
    result = []
    for s in available:
        if s in out_of:
            result.append({"size": s, "in_stock": False, "stock_count": 0})
        elif s in low:
            result.append({"size": s, "in_stock": True, "stock_count": 18})
        else:
            result.append({"size": s, "in_stock": True, "stock_count": 340})
    return result


PRODUCTS = [
    {
        "slug": "plastcare-usa-black-latex-5mil",
        "sku": "PLC-BLK-LTX-5",
        "name": "PlastCare USA Elite Black Latex Exam Gloves",
        "brand": "PlastCare USA",
        "material": "latex",
        "color": "Black",
        "thickness_mil": 5.0,
        "texture": "Fingertip Textured",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D3578",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 8.29,
        "price_tiers": tiers(8.29),
        "industries": ["tattoo-body-art", "beauty-personal-care"],
        "sizes": sizes(["S", "M", "L", "XL"]),
        "images": [IMG_BLACK],
        "short_description": "Second-skin stretch and grip for detail work that runs long.",
        "description": "Built for artists who need feel over armor, this 5-mil black latex glove hugs the hand and holds grip even when things get slippery. The fingertip texture keeps small tools from sliding mid-session, and the true black tone doesn't wash out ink or lift color on camera. Powder-free and exam grade, so it holds up to hygiene standards without the chalky residue.",
        "in_stock": True,
    },
    {
        "slug": "adenna-phantom-black-latex",
        "sku": "ADN-PHNTM-BLK",
        "name": "Adenna Phantom Black Latex Powder-Free Exam Gloves",
        "brand": "Adenna",
        "material": "latex",
        "color": "Black",
        "thickness_mil": 4.5,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D3578",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 10.70,
        "price_tiers": tiers(10.70),
        "industries": ["tattoo-body-art", "medical-healthcare"],
        "sizes": sizes(["S", "M", "L", "XL"], low=["XL"]),
        "images": [IMG_BLACK],
        "short_description": "Natural latex flex with a matte black finish that reads clean under studio light.",
        "description": "Adenna Phantom pairs classic latex elasticity with a low-sheen black finish that photographs well and never looks cheap on a clean station. At 4.5 mil it stays sensitive enough for fine linework while still resisting the small tears that come from repeated glove changes. Exam grade and powder-free, with the snug fit latex is known for.",
        "in_stock": True,
    },
    {
        "slug": "skintx-black-nitrile-5mil",
        "sku": "SKX-BLK-NTR-5",
        "name": "SkinTx Onyx Black Nitrile Powder-Free Exam Gloves",
        "brand": "SkinTx",
        "material": "nitrile",
        "color": "Black",
        "thickness_mil": 5.0,
        "texture": "Textured Palm",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 8.49,
        "price_tiers": tiers(8.49),
        "industries": ["tattoo-body-art", "medical-healthcare", "beauty-personal-care"],
        "sizes": sizes(ALL_SIZES),
        "images": [IMG_BLACK],
        "short_description": "The everyday black nitrile box — latex-free, 5 mil, and priced to reorder without thinking twice.",
        "description": "SkinTx Onyx is the box most shops reorder on autopilot. Latex-free nitrile at 5 mil holds up through a full shift without going thin at the fingertips, and the textured palm keeps grip steady on wet or oily surfaces. Full size run from XS to XXL means multi-artist shops can stock one brand for the whole station.",
        "in_stock": True,
    },
    {
        "slug": "blackwork-chloroprene-exam",
        "sku": "BWK-CHL-BLK-4",
        "name": "Blackwork Chloroprene Powder-Free Exam Gloves",
        "brand": "Blackwork",
        "material": "chloroprene",
        "color": "Black",
        "thickness_mil": 4.0,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D6977",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 11.99,
        "price_tiers": tiers(11.99),
        "industries": ["tattoo-body-art", "medical-healthcare", "laboratory-cleanroom"],
        "sizes": sizes(["S", "M", "L", "XL"]),
        "images": [IMG_BLACK],
        "short_description": "Latex-like stretch with nitrile-grade chemical resistance for clients with allergies.",
        "description": "Chloroprene splits the difference between latex comfort and nitrile durability, which makes Blackwork a solid call when a client is latex-sensitive but a thin nitrile still feels stiff. It stretches like latex on the hand, resists punctures better than most latex, and holds a true matte black that doesn't fade after repeated stretching.",
        "in_stock": True,
    },
    {
        "slug": "gloveworks-black-nitrile-textured",
        "sku": "GWK-BLK-NTR-5",
        "name": "GloveWorks Black Textured Nitrile Gloves 5 Mil",
        "brand": "GloveWorks",
        "material": "nitrile",
        "color": "Black",
        "thickness_mil": 5.0,
        "texture": "Textured Palm",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 9.99,
        "price_tiers": tiers(9.99),
        "industries": ["tattoo-body-art", "industrial-automotive"],
        "sizes": sizes(ALL_SIZES),
        "images": [IMG_BLACK],
        "short_description": "A tougher everyday black nitrile for stations that also do shop cleanup and setup.",
        "description": "GloveWorks steps up the durability from a standard exam box without going full industrial. The palm texture grips tattoo machines and cleaning solvents equally well, and the 5-mil wall resists the tears that come from constant on-off use during a busy day. A practical middle-weight glove for shops that need one box to do double duty.",
        "in_stock": True,
    },
    {
        "slug": "adenna-night-angel-black-nitrile-4mil",
        "sku": "ADN-NGHT-BLK-4",
        "name": "Adenna Night Angel Black Nitrile Powder-Free Exam Gloves 4 Mil",
        "brand": "Adenna",
        "material": "nitrile",
        "color": "Black",
        "thickness_mil": 4.0,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 8.99,
        "price_tiers": tiers(8.99),
        "industries": ["tattoo-body-art", "beauty-personal-care"],
        "sizes": sizes(["XS", "S", "M", "L", "XL"]),
        "images": [IMG_BLACK],
        "short_description": "A thinner 4-mil black nitrile built for tactile precision work.",
        "description": "When a session calls for feel over bulk, Night Angel's 4-mil wall keeps tactile sensitivity close to bare-hand while still giving a full nitrile chemical barrier. Popular for fine detail linework and shading where a thicker glove starts to feel clumsy. Not built for heavy abrasion — pair with a heavier box for cleanup tasks.",
        "in_stock": True,
    },
    {
        "slug": "adenna-shadow-black-nitrile-6mil",
        "sku": "ADN-SHDW-BLK-6",
        "name": "Adenna Shadow Black Nitrile Powder-Free Exam Gloves 6 Mil",
        "brand": "Adenna",
        "material": "nitrile",
        "color": "Black",
        "thickness_mil": 6.0,
        "texture": "Diamond-Grip Textured",
        "powder_free": True,
        "grade": "Industrial",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 10.99,
        "price_tiers": tiers(10.99),
        "industries": ["tattoo-body-art", "industrial-automotive"],
        "sizes": sizes(ALL_SIZES),
        "images": [IMG_BLACK],
        "short_description": "A heavier 6-mil diamond-grip build for four-hour sessions and shop maintenance.",
        "description": "Shadow is the box to reach for when gloves keep splitting mid-session. The 6-mil wall and diamond-textured grip hold up through long appointments and double as a capable shop-maintenance glove for equipment handling between clients. Thicker means slightly less tactile feedback, which is the tradeoff for not stopping to reglove twice an hour.",
        "in_stock": True,
    },
    {
        "slug": "skintx-black-latex-exam",
        "sku": "SKX-BLK-LTX-5",
        "name": "SkinTx Black Latex Powder-Free Exam Gloves",
        "brand": "SkinTx",
        "material": "latex",
        "color": "Black",
        "thickness_mil": 5.0,
        "texture": "Fingertip Textured",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D3578",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 7.88,
        "price_tiers": tiers(7.88),
        "industries": ["tattoo-body-art", "beauty-personal-care"],
        "sizes": sizes(["S", "M", "L", "XL"]),
        "images": [IMG_BLACK],
        "short_description": "The lowest-cost black latex box in stock, without cutting corners on stretch.",
        "description": "For shops that go through boxes fast and want latex's natural flexibility without paying a premium, SkinTx delivers the stretch and rebound latex is known for at one of the more accessible price points on the site. Best for clients without latex sensitivity — pair with a nitrile or chloroprene option for allergy cases.",
        "in_stock": True,
    },
    {
        "slug": "adenna-bronze-latex-exam",
        "sku": "ADN-BRNZ-NAT",
        "name": "Adenna Bronze Powder-Free Latex Exam Gloves",
        "brand": "Adenna",
        "material": "latex",
        "color": "Natural",
        "thickness_mil": 5.5,
        "texture": "Fully Textured",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D3578",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 9.49,
        "price_tiers": tiers(9.49),
        "industries": ["medical-healthcare"],
        "sizes": sizes(["S", "M", "L"], out_of=["S", "M", "L"]),
        "images": [IMG_IVORY],
        "short_description": "Fully textured natural latex exam glove for maximum wet and dry grip.",
        "description": "Bronze is fully textured end to end, which makes it the choice for procedures that involve fluids or instruments where grip matters more than a clean cosmetic look. Currently out of stock as demand shifted with tariff-driven supply changes — request a quote and we will confirm the next restock window or source a comparable substitute.",
        "in_stock": False,
    },
    {
        "slug": "ammex-ivory-latex-exam-xs",
        "sku": "AMX-IVRY-LTX",
        "name": "AMMEX Ivory Latex Exam Powder-Free Disposable Gloves",
        "brand": "AMMEX",
        "material": "latex",
        "color": "Ivory",
        "thickness_mil": 4.5,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D3578",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 12.00,
        "price_tiers": tiers(12.00),
        "industries": ["medical-healthcare", "food-service-processing"],
        "sizes": sizes(["XS", "S", "M", "L"]),
        "images": [IMG_IVORY],
        "short_description": "A true extra-small fit that most catalogs skip stocking.",
        "description": "Small-handed staff know the problem: most exam glove runs stop at Small and call it close enough. AMMEX Ivory keeps a real XS in regular rotation, cutting down on the bunching and torn fingertips that come from sizing up. Neutral ivory tone reads clean for front-of-house medical and food-handling settings alike.",
        "in_stock": True,
    },
    {
        "slug": "verdant-chloroprene-teal-4mil",
        "sku": "VRD-TEAL-CHL-4",
        "name": "Verdant Chloroprene Powder-Free Exam Gloves, Teal Green",
        "brand": "Verdant",
        "material": "chloroprene",
        "color": "Teal Green",
        "thickness_mil": 4.0,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D6977",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 11.90,
        "price_tiers": tiers(11.90),
        "industries": ["medical-healthcare", "laboratory-cleanroom", "food-service-processing"],
        "sizes": sizes(["S", "M", "L", "XL"]),
        "images": [IMG_TEAL],
        "short_description": "Color-coded teal chloroprene for stations that need visual separation from black nitrile lines.",
        "description": "Teal Verdant gives labs, clinics, and prep lines an easy visual way to separate this station's glove supply from a black-nitrile line elsewhere in the building, without giving up chloroprene's latex-like comfort. Handles routine chemical exposure well and holds shape through long shifts.",
        "in_stock": True,
    },
    {
        "slug": "adenna-miracle-blue-nitrile-xs",
        "sku": "ADN-MRCL-BLU-XS",
        "name": "Adenna Miracle Blue Nitrile Powder-Free Exam Gloves",
        "brand": "Adenna",
        "material": "nitrile",
        "color": "Blue",
        "thickness_mil": 3.5,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 200,
        "boxes_per_case": 10,
        "price_per_box": 23.00,
        "price_tiers": tiers(23.00),
        "industries": ["medical-healthcare"],
        "sizes": sizes(["XS", "S", "M"]),
        "images": [IMG_BLUE],
        "short_description": "Double-count 200-glove box in true extra-small, priced per box accordingly.",
        "description": "Miracle Blue packs 200 gloves per box instead of the usual 100, which is why the per-box price runs higher — the per-glove cost is actually competitive once you divide it out. A true XS fit for smaller hands, at a thin 3.5 mil for maximum dexterity in exam settings.",
        "in_stock": True,
    },
    {
        "slug": "proworks-blue-nitrile-exam",
        "sku": "PWK-BLU-NTR-3",
        "name": "ProWorks Blue Nitrile Powder-Free Exam Gloves",
        "brand": "ProWorks",
        "material": "nitrile",
        "color": "Blue",
        "thickness_mil": 3.0,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 4.99,
        "price_tiers": tiers(4.99),
        "industries": ["food-service-processing", "industrial-automotive", "medical-healthcare"],
        "sizes": sizes(ALL_SIZES),
        "images": [IMG_BLUE],
        "short_description": "The lowest-cost box on the site — a lightweight everyday nitrile for high-volume use.",
        "description": "ProWorks Blue is the value option for teams going through cases fast: prep stations, cleanup crews, and back-of-house roles where a lighter 3-mil glove gets swapped often anyway. Not built for heavy chemical or abrasion exposure, but hard to beat on cost per box at case quantity.",
        "in_stock": True,
    },
    {
        "slug": "medline-fitguard-nitrile-violet",
        "sku": "MDL-FTGD-VIO",
        "name": "Medline FitGuard Nitrile Exam Grade Powder-Free Gloves",
        "brand": "Medline",
        "material": "nitrile",
        "color": "Violet",
        "thickness_mil": 3.5,
        "texture": "Textured Fingertip",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 250,
        "boxes_per_case": 8,
        "price_per_box": 14.99,
        "price_tiers": tiers(14.99),
        "industries": ["medical-healthcare", "laboratory-cleanroom"],
        "sizes": sizes(["XS", "S", "M", "L", "XL"]),
        "images": [IMG_VIOLET],
        "short_description": "A 250-count box from a recognized clinical brand, priced per glove rather than per hundred.",
        "description": "FitGuard's 250-glove box means fewer box changes during a shift, from a brand office managers already recognize on compliance paperwork. The violet tone is easy to spot in a supply closet next to other colorways, and the textured fingertip holds instruments securely during exams.",
        "in_stock": True,
    },
    {
        "slug": "gloveworks-blue-nitrile-industrial-6mil",
        "sku": "GWK-BLU-NTR-6",
        "name": "GloveWorks Blue Industrial Nitrile Gloves 6 Mil",
        "brand": "GloveWorks",
        "material": "nitrile",
        "color": "Blue",
        "thickness_mil": 6.0,
        "texture": "Diamond-Grip Textured",
        "powder_free": True,
        "grade": "Industrial",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 9.49,
        "price_tiers": tiers(9.49),
        "industries": ["industrial-automotive", "food-service-processing"],
        "sizes": sizes(["M", "L", "XL", "XXL"]),
        "images": [IMG_BLUE],
        "short_description": "Higher-visibility blue at industrial thickness for shop floors and wash-down areas.",
        "description": "Blue reads clearly against dark equipment and stainless surfaces, which matters on a shop floor where a dropped glove needs to be spotted fast. Six-mil diamond texture holds grip through grease and degreaser exposure. Stocked in mid-to-large sizes for typical industrial hand sizing.",
        "in_stock": True,
    },
    {
        "slug": "ammex-black-nitrile-diamond-8mil",
        "sku": "AMX-BLK-NTR-8",
        "name": "AMMEX Black Diamond Grip Industrial Nitrile Gloves 8 Mil",
        "brand": "AMMEX",
        "material": "nitrile",
        "color": "Black",
        "thickness_mil": 8.0,
        "texture": "Diamond-Grip Textured",
        "powder_free": True,
        "grade": "Industrial",
        "astm_standard": "ASTM D6319",
        "gloves_per_box": 90,
        "boxes_per_case": 10,
        "price_per_box": 16.99,
        "price_tiers": tiers(16.99),
        "industries": ["industrial-automotive"],
        "sizes": sizes(["M", "L", "XL", "XXL"], low=["XXL"]),
        "images": [IMG_BLACK],
        "short_description": "The heaviest wall on the site for degreasing, solvents, and rough handling.",
        "description": "At 8 mil this is built for hands-on mechanical and automotive work rather than exam-room precision — thicker walls, an aggressive diamond grip, and a chemical barrier that holds up against oils, fuels, and common solvents better than exam-grade boxes. Fewer gloves per box at this thickness, but each one does more work.",
        "in_stock": True,
    },
    {
        "slug": "proworks-blue-nitrile-food-grade-3mil",
        "sku": "PWK-BLU-FDG-3",
        "name": "ProWorks High-Visibility Blue Food-Grade Nitrile Gloves",
        "brand": "ProWorks",
        "material": "nitrile",
        "color": "Blue",
        "thickness_mil": 3.0,
        "texture": "Textured Fingertip",
        "powder_free": True,
        "grade": "Food Safe",
        "astm_standard": "FDA 21 CFR 177.2600",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 5.99,
        "price_tiers": tiers(5.99),
        "industries": ["food-service-processing"],
        "sizes": sizes(["S", "M", "L", "XL"]),
        "images": [IMG_BLUE],
        "short_description": "High-visibility blue for food-contact surfaces, meeting FDA food-contact standards.",
        "description": "Standard blue is a food-service norm because it shows up instantly against most ingredients if a glove tears mid-prep. Meets FDA food-contact material standards, textured at the fingertips for handling small or wet product. Ask about case volume — this is one of the lines being expanded as we grow stock for food-service accounts.",
        "in_stock": True,
    },
    {
        "slug": "medline-fitguard-violet-nitrile-chemo",
        "sku": "MDL-FTGD-VIO-CHM",
        "name": "Medline FitGuard Violet Chemo-Rated Nitrile Gloves",
        "brand": "Medline",
        "material": "nitrile",
        "color": "Violet",
        "thickness_mil": 5.1,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Chemo-Tested",
        "astm_standard": "ASTM D6978",
        "gloves_per_box": 100,
        "boxes_per_case": 8,
        "price_per_box": 17.99,
        "price_tiers": tiers(17.99),
        "industries": ["medical-healthcare", "laboratory-cleanroom"],
        "sizes": sizes(["S", "M", "L", "XL"]),
        "images": [IMG_VIOLET],
        "short_description": "ASTM D6978 chemo-tested nitrile for handling hazardous drugs and lab reagents.",
        "description": "Tested to ASTM D6978 for chemotherapy drug permeation, this is the box for lab and clinical settings handling hazardous compounds where an exam-grade glove isn't rated for the job. Stock here is limited — this is one of the categories a quote request helps us source ahead of your need date.",
        "in_stock": True,
    },
    {
        "slug": "skintx-ivory-latex-sensitive",
        "sku": "SKX-IVRY-LTX-4",
        "name": "SkinTx Ivory Latex Sensitive-Skin Exam Gloves",
        "brand": "SkinTx",
        "material": "latex",
        "color": "Ivory",
        "thickness_mil": 4.0,
        "texture": "Smooth",
        "powder_free": True,
        "grade": "Exam",
        "astm_standard": "ASTM D3578",
        "gloves_per_box": 100,
        "boxes_per_case": 10,
        "price_per_box": 9.29,
        "price_tiers": tiers(9.29),
        "industries": ["beauty-personal-care", "medical-healthcare"],
        "sizes": sizes(["XS", "S", "M", "L"]),
        "images": [IMG_IVORY],
        "short_description": "A lighter-weight latex box for color, wax, and skincare work.",
        "description": "Thinner and softer than SkinTx's black latex line, this ivory box is aimed at beauty and personal-care work where clients notice a heavy glove immediately — color application, waxing, and skincare treatments. Full latex stretch with a lower-profile feel.",
        "in_stock": True,
    },
    {
        "slug": "blackwork-black-chloroprene-industrial",
        "sku": "BWK-BLK-CHL-6",
        "name": "Blackwork Black Chloroprene Heavy-Cuff Industrial Gloves",
        "brand": "Blackwork",
        "material": "chloroprene",
        "color": "Black",
        "thickness_mil": 6.0,
        "texture": "Textured Palm",
        "powder_free": True,
        "grade": "Industrial",
        "astm_standard": "ASTM D6977",
        "gloves_per_box": 90,
        "boxes_per_case": 10,
        "price_per_box": 13.50,
        "price_tiers": tiers(13.50),
        "industries": ["industrial-automotive", "laboratory-cleanroom"],
        "sizes": sizes(["M", "L", "XL", "XXL"]),
        "images": [IMG_BLACK],
        "short_description": "Extended cuff chloroprene for splash protection during lab and industrial handling.",
        "description": "The extended cuff on this Blackwork line adds splash coverage past the wrist, useful in labs and industrial settings where liquid exposure runs higher than a standard exam cuff. Chloroprene's chemical resistance holds up to solvents that would degrade latex quickly.",
        "in_stock": True,
    },
]
